// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/building":{"get":{"description":"Get buildings by filters","consumes":["application/json"],"produces":["application/json"],"tags":["buildings"],"summary":"Get buildings","parameters":[{"type":"string","description":"Building ID","name":"id","in":"query"},{"type":"string","description":"Building name","name":"name","in":"query"},{"type":"string","description":"Building city","name":"city","in":"query"},{"type":"string","description":"Year of construction","name":"year","in":"query"},{"type":"string","description":"Number of floors","name":"floor","in":"query"}],"responses":{"200":{"description":"OK","schema":{"type":"array","items":{"$ref":"#/definitions/domain.Building"}}},"400":{"description":"Invalid input","schema":{"type":"string"}}}},"post":{"description":"Create a new building with the provided details","consumes":["application/json"],"produces":["application/json"],"tags":["buildings"],"summary":"Create a new building","parameters":[{"description":"Building","name":"building","in":"body","required":true,"schema":{"$ref":"#/definitions/domain.Building"}}],"responses":{"200":{"description":"The building has been successfully created","schema":{"type":"string"}},"400":{"description":"Invalid input","schema":{"type":"string"}}}}}},"definitions":{"domain.Building":{"type":"object","properties":{"city":{"description":"Город, где находится здание","type":"string"},"floor":{"description":"Количество этажей","type":"string"},"id":{"description":"Уникальный идентификатор здания","type":"integer"},"name":{"description":"Название здания","type":"string"},"year":{"description":"Год постройки","type":"string"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "89.46.131.181:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Building API",
	Description:      "Тестовое задание для компании leadgen",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
